---
name: AgstackPipelines
volumes:
  - volume: mmrs-data
    claim_name: mmrs-data-pvc
    local:
      path: .
images:
  - image: agstack-1.labs.hpe.com:5000/mmrs-python
    type: python
    source: .
pipelines:
  - pipeline: agstack_mmrs_pipeline
    owner: Agstack
    start_date: 2021-10-22
    timeout_minutes: 5
    schedule: "*/10 * * * *"
    tasks:
      - task: mmrs_download
        type: python
        description: download mmrs data
        image: agstack-1.labs.hpe.com:5000/mmrs-python:latest
        mounts:
          - mount: mymount
            volume: gettingstartedvol
            path: /mnt/data
        cmd: pytest mrms_inventory.py --start -3 --end 1 /mnt/data