---
name: GettingStartedPipeline
volumes:
  - volume: gettingstartedvol
    claim_name: gettingstartedvol-pvc
    local:
      path: .
images:
  - image: agstack-1.labs.hpe.com:5000/mmrs-python
    type: python
    source: .
pipelines:
  - pipeline: getting_started_pipeline
    owner: Bosco Albert Baracus
    start_date: 1970-01-01
    timeout_minutes: 10
    schedule: 0 * 1 * *
    default_arg_loaded: check
    default_array_loaded: [2, 3, 4]
    default_object_loaded:
      key1: val1
      key2: val2
    metrics:
      namespace: TestNamespace
      backends: [ ]
    tasks:
      - task: mmrs_download
        type: python
        description: download mmrs data
        image: agstack-1.labs.hpe.com:5000/mmrs-python:latest
        env_vars:
          env1: "a"
          env2: "b"
        mounts:
          - mount: mymount
            volume: gettingstartedvol
            path: /mnt/gettingstartedvol
        cmd: python -u test_mrms_download.py