---
name: AgstackPipelines
volumes:
  - volume: mmrs-data
    claim_name: mmrs-data-pvc
images:
  - image: agstack-1.labs.hpe.com:5000/mmrs-python
    type: python
    source: .
pipelines:
  - pipeline: agstack_mmrs_pipeline
    owner: Agstack
    start_date: 2021-10-22
    timeout_minutes: 5
    schedule: "*/10 * * * *"
    tasks:
      - task: mmrs_inventory_download
        type: python
        description: download mmrs inventory
        image: agstack-1.labs.hpe.com:5000/mmrs-python:latest
        mounts:
          - mount: mmrs-data-mount
            volume: mmrs-data
            path: /mnt/
        cmd: "python3 -u mrms_inventory.py --start -3 --end 1 /mnt/inv"
      - task: mmrs_data_download
        type: python
        description: download mmrs data from inventory
        image: agstack-1.labs.hpe.com:5000/mmrs-python:latest
        mounts:
          - mount: mmrs-data-mount
            volume: mmrs-data
            path: /mnt/
        cmd: "python3 -u mrms_download.py --inventory /mnt/inv --out /mnt/data"
