---
name: AgstackPipeline
volumes:
  - volume: gettingstartedvol
    claim_name: gettingstartedvol-pvc
    local:
      path: .
images:
  - image: agstack-1.labs.hpe.com:5000/mmrs-python
    type: python
    source: .
pipelines:
  - pipeline: agstack_mmrs_pipeline
    owner: Agstack
    start_date: 2020-10-22
    timeout_minutes: 1
    schedule: "*/1 * * * *"
    tasks:
      - task: mmrs_download
        type: python
        description: test download mmrs data
        image: agstack-1.labs.hpe.com:5000/mmrs-python:latest
        mounts:
          - mount: mymount
            volume: gettingstartedvol
            path: /mnt/gettingstartedvol
        cmd: pytest test_mrms_download.py