apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gettingstartedvol-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath